# tomcat
server:
  port: 8002
spring:
  application:
    name: ningshanshui-backup

# backup datasource
ningshanshui:
  backup:
    datasource:
      host: 127.0.0.1
      userName: root
      password: 123456
      database: ningshanshui